In [331]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [332]:
df=pd.read_csv("Data/census_data.csv")
df.head()

,Age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,makes over
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [333]:
df.duplicated().sum()

24

In [334]:
df[df.duplicated()]

,Age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,makes over
4880,25,Private,308144,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
5103,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
9170,21,Private,250051,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
11630,20,Private,107658,Some-college,10,Never-married,Tech-support,Not-in-family,White,Female,0,0,10,United-States,<=50K
13083,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
15058,21,Private,243368,Preschool,1,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,50,Mexico,<=50K
17039,46,Private,173243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
18554,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,?,<=50K
18697,19,Private,97261,HS-grad,9,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,40,United-States,<=50K
21317,19,Private,138153,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,10,United-States,<=50K
21489,19,Private,146679,Some-college,10,Never-married,Exec-managerial,Own-child,Black,Male,0,0,30,United-States,<=50K
21874,49,Private,31267,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
22299,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
22366,44,Private,367749,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,45,Mexico,<=50K
22493,49,Self-emp-not-inc,43479,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
25871,23,Private,240137,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,55,Mexico,<=50K
26312,28,Private,274679,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,50,United-States,<=50K
28229,27,Private,255582,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
28521,42,Private,204235,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
28845,39,Private,30916,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29156,38,Private,207202,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K
30844,46,Private,133616,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
31992,19,Private,251579,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,14,United-States,<=50K
32403,35,Private,379959,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K

In [335]:
df=df.drop_duplicates()

In [336]:
df.shape

(32536, 15)

In [337]:
df

,Age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,makes over
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [338]:
#Independent and dependent features
X = df.drop(labels=['makes over'],axis=1)
y= df[['makes over']]

In [339]:
y

      makes over
0          <=50K
1          <=50K
2          <=50K
3          <=50K
4          <=50K
...          ...
32555      <=50K
32556       >50K
32557      <=50K
32558      <=50K
32559       >50K

[32536 rows x 1 columns]

In [340]:
# Define which columns should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [341]:
# Define the custom ranking for ordinal and categorical variable

In [342]:
makesover_catagories= ['<=50K', '>50K']

In [343]:
workclass_categories= ['Self-emp-not-inc', 'Private', 'State-gov','Federal-gov','Local-gov','others','Self-emp-inc','Without-pay',' Never-worked']

In [344]:
education_categories = ['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college', 'Assoc-acdm','Assoc-voc','7th-8th',' Doctorate','Prof-school','5th-6th',' 10th',' 1st-4th','Preschool',' 12th']

In [345]:

marital_status_categories = ['Married-civ-spouse',' Divorced',' Married-spouse-absent',' Never-married',' Separated',' Married-AF-spouse',' Widowed']

In [346]:

occupation_categories=['Exec-managerial',' Handlers-cleaners',' Prof-specialty','Other-service','Adm-clerical',' Sales',' Craft-repair',' Transport-moving','Farming-fishing',' Machine-op-inspct',' Tech-support',' others',' Protective-serv',' Armed-Forces',' Priv-house-serv']

In [347]:
relationship_categories=[' Husband',' Not-in-family',' Wife',' Own-child',' Unmarried',' Other-relative']

In [348]:
race_categories=[' White',' Black',' Asian-Pac-Islander',' Amer-Indian-Eskimo',' Other']

In [349]:
sex_categories=[' Male','Female']

In [350]:

native_country_categories=['United-States',' Cuba',' Jamaica',' India','others',' Mexico',' South',' Puerto-Rico',' Honduras',' England',' Canada',' Germany',' Iran',' Philippines',' Italy',' Poland',' Columbia',' Cambodia','Thailand',' Ecuador',' Laos',' Taiwan',' Haiti',' Portugal',' Dominican-Republic',' El-Salvador',' France',' Guatemala',' China',' Japan',' Yugoslavia',' Peru',' Outlying-US(Guam-USVI-etc)',' Scotland',' Trinadad&Tobago',' Greece',' Nicaragua',' Vietnam',' Hong',' Ireland',' Hungary',' Holand-Netherlands']

In [351]:
categories1=[workclass_categories,education_categories,marital_status_categories,occupation_categories,relationship_categories,race_categories,sex_categories,native_country_categories]

In [352]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ("onehot",OneHotEncoder(categories=[categories1], sparse=False)),
    ('ordinalencoder',OrdinalEncoder(categories=[makesover_catagories])),
    ('scaler',StandardScaler())
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])


# Define the final pipeline by combining the preprocessor with the logistic regression model
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

In [353]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [354]:
X_train.shape

(22775, 14)

In [355]:
X_test.shape

(9761, 14)

In [356]:
y_train.shape

(22775, 1)

In [357]:
y_test.shape

(9761, 1)

In [358]:
df.shape

(32536, 15)

In [359]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

c:\Users\Vision\OneDrive\Desktop\Logistic_Regression_Project\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [ ]:
X.shape

(32536, 14)

In [ ]:
X_train.shape

(22775, 14)

In [ ]:
X_test.shape

(9761, 14)

In [ ]:
X_train.head()

,num_pipeline__Age,num_pipeline__workclass,num_pipeline__fnlwgt,num_pipeline__education,num_pipeline__education-num,num_pipeline__marital-status,num_pipeline__occupation,num_pipeline__relationship,num_pipeline__race,num_pipeline__sex,num_pipeline__capital-gain,num_pipeline__capital-loss,num_pipeline__hours-per-week,num_pipeline__native-country
0,-1.365004,0.66160,-1.428136,0.286138,-0.031996,-0.087934,-1.901688,-0.101924,0.411966,-1.422732,-0.146308,-0.219699,-0.043786,0.337652
1,-0.412388,-1.50921,-0.257893,1.142226,-0.421682,-1.451683,-1.155679,-0.101924,-2.564333,-1.422732,-0.146308,-0.219699,0.036968,-2.983814
2,-0.558944,0.66160,0.484434,-0.228261,1.137062,-0.087934,0.428385,-0.101924,0.411966,0.702873,-0.146308,-0.219699,-0.043786,0.337652
3,-1.365004,0.66160,1.191955,-1.341549,-1.201054,-0.087934,0.113676,-0.874651,-2.332512,0.702873,-0.067070,-0.219699,-1.658869,0.337652
4,1.785956,0.66160,-0.608883,1.142226,-0.421682,-0.087934,-1.018049,-0.101924,0.411966,0.702873,0.143698,-0.219699,-0.043786,0.337652

In [ ]:
X_test.head()

,num_pipeline__Age,num_pipeline__workclass,num_pipeline__fnlwgt,num_pipeline__education,num_pipeline__education-num,num_pipeline__marital-status,num_pipeline__occupation,num_pipeline__relationship,num_pipeline__race,num_pipeline__sex,num_pipeline__capital-gain,num_pipeline__capital-loss,num_pipeline__hours-per-week,num_pipeline__native-country
0,-0.998613,0.661600,1.359013,-1.517724,-1.980426,0.854969,-1.018049,1.070457,0.411966,0.702873,-0.146308,-0.219699,0.359984,0.337652
1,1.126453,-1.600472,-1.542247,1.142226,-0.421682,0.854969,0.530950,1.070457,0.411966,0.702873,-0.146308,-0.219699,-0.043786,0.337652
2,0.466950,-1.482436,-0.135162,-1.517724,-1.980426,-0.087934,0.113676,-0.874651,0.411966,0.702873,-0.146308,-0.219699,-0.043786,0.337652
3,-0.558944,0.661600,1.977747,0.286138,-0.031996,-0.087934,0.792185,-0.101924,0.411966,0.702873,-0.146308,-0.219699,-0.043786,0.337652
4,2.738572,-1.435867,-1.487479,-1.195758,1.526748,0.854969,0.854425,1.070457,0.411966,0.702873,-0.146308,-0.219699,-0.851328,-2.925899

In [ ]:
regression=LogisticRegression()
regression.fit(X_train,y_train)

c:\Users\Vision\OneDrive\Desktop\Logistic_Regression_Project\venv\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [ ]:
regression.fit(X_train,y_train)

c:\Users\Vision\OneDrive\Desktop\Logistic_Regression_Project\venv\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [ ]:
y_pred=regression.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.8416145886691937

In [ ]:
confusion_matrix(y_test,y_pred)

array([[7011,  444],
       [1102, 1204]], dtype=int64)